### PR TITLE
Fix issues with overlay dismissing & update

### LINKED ISSUE #14: onComplete not triggered after onDismiss
Hi,

I have set `onDismiss: () async => false,` to disable dismissing the feature discovery.

Problem is that if I first tap outside the feature overlay area first it works as expected and the feature overlay is not dismissed but later when I tap on the main icon button to complete the feature overlay it does not respond.

If I first tap on the icon button to complete the feature it moves forward to the next step. But in the next step if I again perform the above steps on the second step the same problem appears.

I am using Feature Discovery version 0.6.1 on Android.

Steps:
1. Create a `DescribedFeatureOverlay` with `onDismiss: () async => false`
2. When the app is running and feature discovery is displayed, Tap outside the overlay area to dismiss the overlay (Overlay will not dismiss)
3. Now tap on the icon button to complete the discovery. This time the discovery will not complete.

### PR DESCRIPTION
**Pull request by axel-op**
This PR will fix https://github.com/ayalma/feature_discovery/issues/14.

The problem is simple: when detecting a tap outside an overlay, we directly called the bloc's `dismiss` function. The bloc then would send an event to all the overlays and delete its references to them, without checking if they'd be effectively dismissed.

With this PR, an overlay first tries to dismiss itself before calling the bloc.

I also changed `FeatureDiscovery.dismissAll` behavior: when calling it, all overlays will be forced-dismissed regardless of the returned value of `onDismiss`.

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
I will apply a few tiny patches that I think should be fine. Please have a look at them, nonetheless.

File: lib/src/foundation/bloc.dart [hunk 1]
```diff
@@ -81,7 +81,7 @@ class Bloc {
     _eventsController.close();
   }
 
-  void discoverFeatures({Iterable<String> steps}) {
+  void discoverFeatures({@required Iterable<String> steps}) {
```
Comment (creativecreatorormaybenot) [inline lib/src/foundation/bloc.dart]: This should not be a named parameter. It is technically a public part of the API, but it is not exported in `feature_discovery.dart`. Hence, I am not calling this a breaking change and it should be fine.

File: lib/src/widgets/overlay.dart [hunk 2]
```diff
@@ -358,7 +359,9 @@ class _DescribedFeatureOverlayState extends State<DescribedFeatureOverlay>
     _close();
   }
 
-  Future<void> _dismiss() async {
+  /// If [force] is true, the [onDismiss] function will be awaited
```
Comment (creativecreatorormaybenot) [inline lib/src/widgets/overlay.dart]: If we want to have `dismissAll`, it should be done properly. Convince me that this is needed.  
I think that this could lead to some unexpected behavior, e.g. if you have a future that does not complete straight away, but you want to forcefully dismiss all overlays.

**Comment by creativecreatorormaybenot** [comment]
I just noticed that the Pedantic dependency currently needs an override.

This also made me realize that there are new warnings because of the updated Pedantic version and a few `TextTheme` changes in the upcoming versions of Flutter that deprecate some of the fields we used.

I will commit it to this branch because it really does not matter when we end up pusing it to https://github.com/ayalma/feature_discovery anyways - it is more comfortable right now.

**Review by creativecreatorormaybenot — APPROVED** [review]

**Comment by axel-op** [comment]
@creativecreatorormaybenot I squashed some of your commits but added you as co-author.

File: lib/src/foundation/feature_discovery.dart [hunk 3]
```diff
@@ -29,20 +29,20 @@ class FeatureDiscovery extends StatelessWidget {
...
 
   /// This will schedule completion of the current discovery step and continue
   /// onto the step after the completion animation of the current overlay if successful.
   static void completeCurrentStep(BuildContext context) =>
       _blocOf(context).completeStep();
 
-  /// This will schedule dismissal of the current discovery step and with that
-  /// of the current feature discovery. The dismissal animation will play if successful.
+  /// This will dismiss all steps.
+  /// `onDimiss` parameter will be ignored for every active overlay.
```
Comment (axel-op) [inline lib/src/foundation/feature_discovery.dart]: @creativecreatorormaybenot I also edited this documentation. Tell me what you think about it.

Comment (creativecreatorormaybenot) [reply lib/src/foundation/feature_discovery.dart]: I will add an article.

**Comment by creativecreatorormaybenot** [comment]
@axel-op I do not understand; why would you force push here?

Otherwise, I think it looks fine, but did you even add something? Again, I cannot tell because of the force pushes..

**Comment by axel-op** [comment]
> @axel-op I do not understand; why would you force push here?
> This will mess up the Git blame, which is not helpful.
> Otherwise, I think it looks fine, but did you even add something? Again, I cannot tell because of the force pushes..

It was just to keep a clean history, but if this bothers you I won't do it again, sorry.

And no, I didn't add anything except these two lines.

**Comment by creativecreatorormaybenot** [comment]
@axel-op No, you are right. I also think it is nicer to have a clean history. It was just that I added like 3 commits and you condensed it into 2, so yeah.

Also, I think I have seen this work properly, where the lines still had the correct blame. You can e.g. squash it into a single commit when merging, which seems to make sense to me. The Flutter repo does it. I think I will revert your squash because I edited the doc lines anyway and then we can see. Let me know what you think about the updated doc and if you have more insights on squashing - maybe I do not understand it properly. The Git blame just looked wrong to me :)

See  the "Squash and merge" option below on the button.

**Comment by axel-op** [comment]
> You can e.g. squash it into a single commit when merging, which seems to make sense to me. 

Right, we should do that instead

**Review by axel-op — COMMENTED** [review]
Everything seems OK to me

@creativecreatorormaybenot Should we merge?

**Comment by creativecreatorormaybenot** [comment]
You should check again that everything is fine, then yes.
